# Generated by Django 4.1.7 on 2023-03-18 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_scope_options_alter_scope_is_main_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={},
        ),
    ]
