# Generated by Django 4.1.7 on 2023-03-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='date_measure',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата измерения'),
        ),
    ]
