# примеры API-запросов

@baseUrl = http://localhost:8000/api/v1

# создание продукта
POST {{baseUrl}}/products/
Content-Type: application/json

{
  "title": "watermelon",
  "description": ""
}

###

# получение продуктов
GET {{baseUrl}}/products/?ordering=id
Content-Type: application/json

###

# обновление продукта
PATCH {{baseUrl}}/products/5/
Content-Type: application/json

{
  "description": "state of mind"
}

###

# удаление продукта
DELETE {{baseUrl}}/products/3/
Content-Type: application/json

###

# поиск продуктов по названию и описанию
GET {{baseUrl}}/products/?search=straw
Content-Type: application/json

###

# создание склада
POST {{baseUrl}}/stocks/
Content-Type: application/json

{
  "address": "spb",
  "positions": [
    {
      "product": 5,
      "quantity": 10000,
      "price": 10000
    }
  ]
}

###

# обновляем записи на складе
PATCH {{baseUrl}}/stocks/3/
Content-Type: application/json

{
  "positions": [
    {
      "product": 6,
      "quantity": 1000,
      "price": 1000
    }
  ]
}

###

# поиск складов, где есть определенный продукт
GET {{baseUrl}}/stocks/?products=6
Content-Type: application/json

###

# удаление склада
DELETE {{baseUrl}}/stocks/2/
Content-Type: application/json

###

# получение складов
GET {{baseUrl}}/stocks/
Content-Type: application/json

###
